### ISSUE TITLE
ArangoDB security options

### ISSUE THREAD

**Issue by sleepycat** [canada-ca/tracker#3773]
ArangoDB isn't exposed outside the cluster but there are several security options in [the documentation](https://www.arangodb.com/docs/stable/security-security-options.html) that are worth adding to our existing config.
These options would need to be enabled in our `ArangoDeployment` resource (which describes how to configure ArangoDB) like so:
```yaml
spec:
  coordinators:
    args:
      - --server.harden
```

- [ ] server.harden
- [ ] endpoint access
